--- 
- name: Run tasks based on OS
  hosts: all 
  tasks: 
    - name: Group OS
      group_by: 
        key: "{{ ansible_distribution }}"
      
- hosts: CentOS
  become: yes
  become_user: root
  remote_user: centos
  tasks:
    - name: Install on centos 
      package: 
        name: telnet