--- 
- name: Run tasks based on OS
  hosts: localhost 
  tasks: 
    - name: Group OS
      group_by:
        key: "{{ansible_distribution}}"


- hosts: CentOS
  remote_user: centos
  become: yes
  become_user: root
  tasks:
    - name: Install
      package: 
        name: httpd
        state: absent

- hosts: Debian
  become: yes
  become_user: root
  remote_user: admin
  tasks:
    - name: Install 
      package: 
        name: telnet
  
- hosts: Amazon
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks: 
    - name: Install package
      package: 
        name: telnet