--- 
- name: Run tasks based on OS
  hosts: all 
  tasks: 
    - name: Group OS
      group_by:
        key: "{{ansible_distribution}}"


- hosts: CentOS
  tasks:
    - name: Install
      package: 
        name: httpd
        state: latest

