--- 
- name: Run tasks based on OS
  hosts: localhost 
  tasks: 
    - name: Group OS
      group_by: 
        key: "{{ ansible_distribution }}"
      
- hosts: Admin
  remote_user: admin
  tasks:
    - name: Install on debian 
      package: 
        name: telnet