--- 
- name: Run tasks based on OS
  hosts: localhost 
  tasks: 
    - name: Group OS
      group_by:
        key: "{{ansible_distribution}}"




- hosts: "Debian"
  ansible_user: admin
  tasks:
    - name: Install on debian 
      package: 
        name: telnet
  
- hosts: Amazon
  ansible_user: ec2-user
  become: yes
  become_user: root
  tasks: 
    - name: Install package on ec2
      package: 
        name: telnet