--- 
- name: Run tasks based on OS
  hosts: localhost 
  tasks: 
    - name: Group OS
      group_by: 
        key: "{{ansible_distribution}}"


- hosts: Debian
  tasks:
    - name: Install on debian 
      package: 
        name: telnet