--- 
- name: Run tasks based on OS
  hosts: localhost 
  tasks: 
    - name: Group OS
      group_by: key="os_{{ ansible_distribution }}"


- hosts: os_Debian
  ansible_user: admin
  tasks:
    - name: Install on debian 
      package: 
        name: telnet
  